git-debimport resource-agents_4.0.0~rc1-4~bpo8+1.debian.tar.xz

diff --git a/heartbeat/iSCSITarget b/heartbeat/iSCSITarget
--- a/heartbeat/iSCSITarget
+++ b/heartbeat/iSCSITarget
@@ -56,7 +56,7 @@ meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="iSCSITarget" version="0.9">
+<resource-agent name="iSCSITarget">
 <version>0.9</version>
 
 <longdesc lang="en">
@@ -103,6 +103,15 @@ listens on ${OCF_RESKEY_portal_default}.
 </longdesc>
 <shortdesc lang="en">iSCSI portal addresses</shortdesc>
 <content type="string" default="${OCF_RESKEY_portals_default}"/>
+</parameter>
+
+<parameter name="iser_portals" required="0" unique="0">
+<longdesc lang="en">
+iSCSI iSER network portal addresses. Not supported by all
+implementations.
+</longdesc>
+<shortdesc lang="en">iSCSI iSER enabled portal addresses</shortdesc>
+<content type="string"/>
 </parameter>
 
 <parameter name="allowed_initiators" required="0" unique="0">
@@ -347,6 +356,17 @@ iSCSITarget_start() {
 				ocf_log warn "Unsupported iSCSI target parameter ${name}: will be ignored."
 			fi
 		done
+		
+		# allow iSER enabled portal
+		for iser_portal in ${OCF_RESKEY_iser_portals}; do
+                       configfs_path="/sys/kernel/config/target/iscsi/${OCF_RESKEY_iqn}/tpgt_1/np/${iser_portal}\:*/iser"
+                       if [ -f ${configfs_path} ]; then
+                                 echo "1" > ${configfs_path} || exit $OCF_ERR_GENERIC
+                       else
+                                 ocf_log warn "Unable to set iSER on: $iser_portal"
+                       fi
+                done
+		
 		# lio does per-initiator filtering by default. To disable
 		# this, we need to switch the target to "permissive mode".
 		if [ -n "${OCF_RESKEY_allowed_initiators}" ]; then
diff --git a/heartbeat/slapd b/heartbeat/slapd
--- a/heartbeat/slapd
+++ b/heartbeat/slapd
@@ -105,7 +105,7 @@ For example, "/usr/bin/ldapsearch".
 Full path to a slapd configuration directory or a slapd configuration file.
 For example, "/etc/ldap/slapd.d" or "/etc/ldap/slapd.conf".
 </longdesc>
-<shortdesc>Full path to configuration directory or file</shortdesc>
+<shortdesc lang="en">Full path to configuration directory or file</shortdesc>
 <content type="string" default=""/>
 </parameter>
 
@@ -139,7 +139,7 @@ Group name or id slapd will run with.
 LDAP (and other scheme) URLs slapd will serve.
 For example, "ldap://127.0.0.1:389 ldaps:/// ldapi:///"
 </longdesc>
-<shortdesc>LDAP (and other scheme) URLs to serve</shortdesc>
+<shortdesc lang="en">LDAP (and other scheme) URLs to serve</shortdesc>
 <content type="string" default="ldap:///"/>
 </parameter>
 
@@ -150,7 +150,7 @@ suffixes can be specified by providing a space seperated list. By providing one
 or more suffixes here, the ignore_suffix parameter is discarded. All suffixes
 will be monitored if left blank.
 </longdesc>
-<shortdesc>Suffix that will be monitored for availability.</shortdesc>
+<shortdesc lang="en">Suffix that will be monitored for availability.</shortdesc>
 <content type="string" default=""/>
 </parameter>
 
@@ -160,7 +160,7 @@ Suffix (database backend) that will not be monitored for availability. Multiple
 suffixes can be specified by providing a space seperated list. No suffix will
 be excluded if left blank.
 </longdesc>
-<shortdesc>Suffix that will not be monitored for availability.</shortdesc>
+<shortdesc lang="en">Suffix that will not be monitored for availability.</shortdesc>
 <content type="string" default=""/>
 </parameter>
 
@@ -169,7 +169,7 @@ be excluded if left blank.
 Distinguished Name used to bind to the LDAP directory for testing. Leave blank
 to bind to the LDAP directory anonymously.
 </longdesc>
-<shortdesc>Distinguished Name used to bind to the LDAP directory for testing.</shortdesc>
+<shortdesc lang="en">Distinguished Name used to bind to the LDAP directory for testing.</shortdesc>
 <content type="string" default=""/>
 </parameter>
 
@@ -177,7 +177,7 @@ to bind to the LDAP directory anonymously.
 <longdesc lang="en">
 Password used to bind to the LDAP directory for testing.
 </longdesc>
-<shortdesc>Password used to bind to the LDAP directory for testing.</shortdesc>
+<shortdesc lang="en">Password used to bind to the LDAP directory for testing.</shortdesc>
 <content type="string" default=""/>
 </parameter>
 
@@ -217,32 +217,6 @@ Maximum number of open files (for ulimit -n)
 </actions>
 </resource-agent>
 END
-}
-
-terminate()
-{
-  local pid=$1
-  local signal=$2
-  local recheck=${3-0}
-  local rc
-  local waited=0
-
-  kill -$signal $pid >/dev/null 2>&1; rc=$?
-
-  while [ \( $rc -eq 0 \) -a \( $recheck -eq 0 -o $waited -lt $recheck \) ]; do
-    kill -0 $pid >/dev/null 2>&1; rc=$?
-    let "waited += 1"
-
-    if [ $rc -eq 0 ]; then
-      sleep 1
-    fi
-  done
-
-  if [ $rc -ne 0 ]; then
-    return 0
-  fi
-
-  return 1
 }
 
 watch_suffix()
@@ -289,18 +263,12 @@ slapd_pid()
 slapd_status()
 {
   local pid=$1
-  local state=$?
 
-  if [ $state -eq $OCF_SUCCESS ]; then
-
-    if ! kill -0 $pid >/dev/null 2>&1; then
-      return $OCF_NOT_RUNNING
-    else
-      return $OCF_SUCCESS
-    fi
+  if ! kill -0 $pid >/dev/null 2>&1; then
+    return $OCF_NOT_RUNNING
+  else
+    return $OCF_SUCCESS
   fi
-
-  return $state
 }
 
 slapd_start()
@@ -382,10 +350,10 @@ slapd_stop()
     return $state
   fi
 
-  terminate $pid TERM $OCF_RESKEY_stop_escalate; rc=$?
-  if [ $rc -ne 0  ]; then
-    ocf_exit_reason "slapd failed to stop. Escalating to KILL."
-    terminate $pid KILL; rc=$?
+  ocf_stop_processes TERM $OCF_RESKEY_stop_escalate $pid; rc=$?
+  if [ $rc -eq 1 ]; then
+    ocf_log err "cannot stop slapd."
+    return $OCF_ERR_GENERIC
   fi
 
   if [ -f "$pid_file" ]; then
